"use client";

import { useEffect } from "react";
import Link from "next/link";
import { Dumbbell, Brain, Building2, Trophy } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import api from "@/lib/api";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Plans",
    description:
      "Get personalized workout and diet plans generated by AI based on your goals and available equipment.",
  },
  {
    icon: Building2,
    title: "Gym Integration",
    description:
      "Connect with your gym to get workouts tailored to available equipment. Gym owners manage everything in one place.",
  },
  {
    icon: Dumbbell,
    title: "Progress Tracking",
    description:
      "Log every workout, track PRs, monitor weight and BMI trends. AI analyzes your progress and suggests improvements.",
  },
  {
    icon: Trophy,
    title: "Leaderboards",
    description:
      "Compete on global and gym-specific leaderboards. Stay motivated with your community.",
  },
];

export default function LandingPage() {
  // Wake up the backend on Render (free tier sleeps after 15 min inactivity)
  useEffect(() => {
    api.get("/api/health").catch(() => {});
  }, []);

  return (
    <div className="flex min-h-screen flex-col">
      <header className="flex items-center justify-between border-b px-6 py-4">
        <div className="flex items-center gap-2">
          <Dumbbell className="h-8 w-8 text-primary" />
          <span className="text-2xl font-bold">Flexist</span>
        </div>
        <div className="flex gap-2">
          <Link href="/login">
            <Button variant="ghost">Sign In</Button>
          </Link>
          <Link href="/register">
            <Button>Get Started</Button>
          </Link>
        </div>
      </header>

      <main className="flex-1">
        <section className="flex flex-col items-center justify-center gap-6 px-4 py-24 text-center">
          <h1 className="max-w-3xl text-5xl font-bold tracking-tight">
            Your AI Fitness Coach,{" "}
            <span className="text-primary">Powered by Your Gym</span>
          </h1>
          <p className="max-w-xl text-lg text-muted-foreground">
            Personalized workouts, smart diet plans, and progress tracking — all
            tailored to the equipment at your gym.
          </p>
          <div className="flex gap-3">
            <Link href="/register">
              <Button size="lg">Start Free</Button>
            </Link>
            <Link href="/register?role=gym_owner">
              <Button size="lg" variant="outline">
                Register Your Gym
              </Button>
            </Link>
          </div>
        </section>

        <section className="mx-auto grid max-w-5xl gap-6 px-4 pb-24 md:grid-cols-2">
          {features.map((f) => (
            <Card key={f.title}>
              <CardHeader>
                <f.icon className="mb-2 h-10 w-10 text-primary" />
                <CardTitle>{f.title}</CardTitle>
                <CardDescription>{f.description}</CardDescription>
              </CardHeader>
            </Card>
          ))}
        </section>
      </main>

      <footer className="border-t px-6 py-4 text-center text-sm text-muted-foreground space-y-2">
        <p>Flexist &copy; {new Date().getFullYear()}</p>
        <p className="max-w-2xl mx-auto text-xs">
          AI features are powered by OpenAI. When you use AI-generated workout plans, diet plans, or progress analysis,
          your fitness data (weight, height, goals, workout history, and body measurements) is sent to OpenAI for processing.
          AI usage is limited to 5 requests per user per day.
        </p>
      </footer>
    </div>
  );
}
